Pipular/Controllers/ChartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Pipular.Models;
using Pipular.Models.Charts;

namespace Pipular.Controllers
{
    public class ChartController : Controller
    {
        // JSON

        pipularEntities DB = new pipularEntities();

        [HttpGet]
        [CompressFilter]
        public JsonResult SystemHistory(int id, DateTime? start, DateTime? stop)
        {
            return ConnectHistory(id, 0, start, stop);
        }

        [HttpGet]
        [CompressFilter]
        public JsonResult SystemMiniHistory()
        {
            var profit = from p in DB.daily_profit
                         where p.connect == 0 && p.System_.enabled == 1
                         group p by p.system into pGroup
                         select new
                         {
                             system = pGroup.Key,
                             profit = from pg in pGroup
                                      orderby pg.date
                                      select new ProfitChart
                                      {
                                          date = pg.date,
                                          pl = pg.pl,
                                          pts = pg.pts
                                      }
                         };

            return this.Json(profit, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [CompressFilter]
        public JsonResult ConnectHistory(int system, int connect, DateTime? start, DateTime? stop)
        {
            return GetHistory(system, connect, start, stop);
        }

        public JsonResult GetHistory(int system, int connect, DateTime? start, DateTime? stop)
        {
            var dailyProfit = start.HasValue && stop.HasValue ? GetDailyProfit(system, connect, start.Value, stop.Value) : GetDailyProfit(system, connect);
            var dailyDD = start.HasValue && stop.HasValue ? GetDailyDD(system, connect, start.Value, stop.Value) : GetDailyDD(system, connect);

            var chart = new { profit = dailyProfit, drawdown = dailyDD };

            return this.Json(chart, JsonRequestBehavior.AllowGet);
        }

        private IQueryable<ProfitChart> GetDailyProfit(int system, int connect)
        {
            return from dp in DB.daily_profit
                   where dp.system == system && dp.connect == connect
                   select new ProfitChart
                   {
                       pl = dp.pl,
                       pts = dp.pts,
                       date = dp.date
                   };
        }

        private IQueryable<ProfitChart> GetDailyProfit(int system, int connect, DateTime start, DateTime stop)
        {
            return GetDailyProfit(system, connect).Where(p => p.date > start && p.date <= stop);
        }

        private IQueryable<DailyDD> GetDailyDD(int system, int connect)
        {
            return from dd in DB.daily_dd
                   where dd.system == system && dd.connect == connect
                   select new DailyDD
                   {
                       dd = dd.dd,
                       dd_pip = dd.dd_pip,
                       date = dd.date
                   };
        }

        private IQueryable<DailyDD> GetDailyDD(int system, int connect, DateTime start, DateTime stop)
        {
            return GetDailyDD(system, connect).Where(d => d.date > start && d.date <= stop);
        }
    }
}

Pipular/Controllers/PrivateController.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Pipular.Models;
using Pipular.Models.Charts;
using System.Configuration;
using System.Data.Objects.DataClasses;
using System.ComponentModel;
using System.Text.RegularExpressions;
using System.Threading;
using System.Globalization;
using NLog;
using MathNet.Numerics;
using MathNet.Numerics.Distributions;

namespace Pipular.Controllers
{
    public class PrivateController : BaseController
    {
        BackgroundWorker bw = new BackgroundWorker();
        SERV3 serv3 = new SERV3();

        #region Download PipRunner
        [Authorize]
        public FilePathResult GetPipRunner()
        {
            string path = AppDomain.CurrentDomain.BaseDirectory + "soft/";

            List<FileNames> file_list = GetFiles(path);

            if (!file_list.Any()) return null;

            FileNames file = file_list.OrderByDescending(f => f.version).First();

            int user_nmbr = int.Parse(User.Identity.Name);

            DB.users.First(u => u.nmbr == user_nmbr).soft = file.version;
            DB.SaveChanges();

            Response.Cookies["new_version"].Expires = DateTime.Now.AddDays(-1);

            string fileName = file.name;
            return File(path + fileName, "text/plain", fileName);
        }
        
        public class FileNames
        {
            public int version { get; set; }
            public string name { get; set; }
        }

        public static List<FileNames> GetFiles(string path)
        {
            List<FileNames> file_list = new List<FileNames>();
            DirectoryInfo dirInfo = new DirectoryInfo(path);
            Regex regex = new Regex(@"(?<=\(version )(\d+)(?=\))");

            foreach (FileInfo item in dirInfo.GetFiles())
            {
                int ver;

                if(!int.TryParse(regex.Match(item.Name).Value, out ver)) ver = 0;

                file_list.Add(new FileNames()
                {
                    name = item.Name,
                    version = ver
                });
            }

            return file_list;
        }
        #endregion

        // DASHBOARD -----------------------------------------------------
        
        #region Dashboard
        [Authorize]
        public ActionResult Dashboard()
        {
            int user_nmbr = int.Parse(User.Identity.Name);

            ViewBag.Portfolios = GetUserPortfolios(user_nmbr);

            ViewBag.Copies = GetUserCopies(user_nmbr);

            ViewBag.Systems = GetUserSystems(user_nmbr);

            return View();
        } 
        #endregion

        // follow panel

        #region Portfolio switch
        [Authorize]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        public EmptyResult PortfolioSwitch(int id)
        {
            try
            {
                account acc = DB.accounts.Single(a => a.nmbr == id);
                acc.@public = acc.@public == 0 ? 1 : 0;

                DB.SaveChanges();
            }
            catch { }

            return null;
        }
        #endregion

        #region Portfolio delete (delete account)
        [Authorize]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        public ActionResult PortfolioDelete(int id)
        {
            int user_nmbr = int.Parse(User.Identity.Name);

            Message mess = new Message();

            try
            {
                account acc = DB.accounts.Single(a => a.nmbr == id && a.user == user_nmbr);
                if (acc != null)
                {
                    DB.accounts.DeleteObject(acc);

                    IEnumerable<connect> connects = from c in DB.connects
                                                    where c.account2 == acc.nmbr
                                                    select c;
                    foreach (connect c in connects)
                    {
                        c.account2 = 0;
                    }

                    IEnumerable<trade> delete = from t in DB.trades
                                                join c in DB.connects on t.connect equals c.nmbr
                                                select t;
                    foreach (trade t in delete)
                        DB.trades.DeleteObject(t);

                    DB.SaveChanges(); 
                }
            }
            catch (Exception error)
            {
                mess.text = error.Message + error.InnerException;
                mess.type = MessageType.Bad;

                return PartialView("Message", mess);
            }

            mess.text = "Portfolio successfully removed.";
            mess.type = MessageType.Good;

            return PartialView("Message", mess);
        }
        #endregion

        #region Connect block
        [Authorize]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        public ActionResult ConnectBlock(int id)
        {
            ConnectModel model = GetConnect(id);

            return PartialView(model);
        } 
        #endregion

        #region Change portfolio
        [Authorize]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        public ActionResult ChangePortfolio(int id, int account)
        {
            ConnectModel model = new ConnectModel();

            try
            {
                connect con = DB.connects.Single(c => c.nmbr == id);
                con.account2 = account;
                con.dt_last = DateTime.UtcNow;
                DB.SaveChanges();

                bw.DoWork += serv3.SendCMD;
                bw.RunWorkerAsync(new string[] { "EDIT_CONNECT", "connects", id.ToString(), User.Identity.Name });
            }
            catch { }

            return RedirectToAction("ConnectBlock", new { id = id });
        } 
        #endregion

        #region ConnectSwitch
        [Authorize]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        public ActionResult ConnectSwitch(int id)
        {
            connect con = DB.connects.First(c => c.nmbr == id);

            con.enabled = (con.enabled == 1) ? 0 : 1;
            con.dt_last = DateTime.UtcNow;

            DB.SaveChanges();

            bw.DoWork += serv3.SendCMD;
            bw.RunWorkerAsync(new string[] { "EDIT_CONNECT", "connects", con.nmbr.ToString(), User.Identity.Name });

            return RedirectToAction("ConnectBlock", new { id = id });
        } 
        #endregion

        #region Connect delete
        [Authorize]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        public ActionResult ConnectDelete(int id)
        {
            Message mess = new Message();
            
            try
            {
                connect con = DB.connects.First(c => c.nmbr == id);

                con.enabled = 2;
                con.dt_last = DateTime.UtcNow;

                DB.SaveChanges();

                bw.DoWork += serv3.SendCMD;
                bw.RunWorkerAsync(new string[] { "DEL_CONNECT", "connects", con.nmbr.ToString(), User.Identity.Name });

                mess.text = "Connect deleted successfully.";
                mess.type = MessageType.Good;
            }
            catch (Exception error) 
            {
                mess.type = MessageType.Bad;
                mess.text = error.Message;
            }

            return PartialView("Message", mess);
        }
        #endregion

        #region Sending type switch
        [Authorize]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        public ActionResult SendingTypeSwitch(int id, int type)
        {
            try
            {
                connect con = DB.connects.First(c => c.nmbr == id);

                switch (type)
                {
                    case 1: // MT4
                        if (con.mt4 == 1) con.mt4 = 0;
                        else con.mt4 = 1;
                        break;
                    case 2: // EMAIL
                        if (con.email == 1) con.email = 0;
                        else con.email = 1;
                        break;
                    case 3: // ICQ
                        if (con.icq == 1) con.icq = 0;
                        else con.icq = 1;
                        break;
                    case 4: // PHONE
                        if (con.phone == 1) con.phone = 0;
                        else con.phone = 1;
                        break;
                    case 5: // SKYPE
                        if (con.skype == 1) con.skype = 0;
                        else con.skype = 1;
                        break;
                }

                con.dt_last = DateTime.UtcNow;

                DB.SaveChanges();

                bw.DoWork += serv3.SendCMD;
                bw.RunWorkerAsync(new string[] { "EDIT_CONNECT", "connects", con.nmbr.ToString(), User.Identity.Name });
            }
            catch { }

            return RedirectToAction("ConnectBlock", new { id = id });
        }
        #endregion

        #region Connect copy
        [Authorize]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        public ActionResult ConnectCopy(int id, int account)
        {
            try
            {
                connect con = DB.connects.First(c => c.nmbr == id);
                
                connect new_con = new connect()
                    {
                        account = con.account,
                        account2 = account,
                        dt_last = DateTime.UtcNow,
                        dt_create = DateTime.UtcNow,
                        email = con.email,
                        enabled = con.enabled,
                        icq = con.icq,
                        mt4 = con.mt4,
                        phone = con.phone,
                        portfolio = con.portfolio,
                        skype = con.skype,

Pipular/Views/Private/Accounts.cshtml
@using Pipular.Models;
@{
    ViewBag.Title = "My accounts";
}

<h2>My accounts</h2>
<table>
    <thead>
        <tr>
            <th>
                Number
            </th>
            <th>
                Company
            </th>
            <th>
                Server
            </th>
            <th>
                Balance
            </th>
            <th>
                Equity
            </th>
            <th>
                Online
            </th>
            <th>
                Last update
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (account item in (List<account>)ViewData["Account_list"])
        {
            <tr>
                <td>
                    @item.number
                </td>
                <td>
                    @item.company
                </td>
                <td>
                    @item.server
                </td>
                <td>
                    @item.balance
                </td>
                <td>
                    @item.equity
                </td>
                <td>
                    @item.serv3online
                </td>
                <td>
                    @item.dt_last
                </td>
            </tr>
}
    </tbody>
</table>

Pipular/Views/Private/AddPortfolio.cshtml
@using Pipular.Models;
@model PortfolioModel

@{string portf_id = "Portfolio" + Model.id;}

<div id="@portf_id" class="portfolio" style="margin: 5px;border: 1px solid black; padding: 5px;">
    @Html.Partial("Portfolio", Model, ViewData)
</div>

Pipular/Views/Private/AddSystem.cshtml
@model Pipular.Models.AddSystemModel

@{
    ViewBag.Title = "Add new system";
}

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

<div id="addNewSystem">
    <div class="head">
        <span><b>Add new system</b></span>
        (<a onclick="closeAddit()">cancel</a>)
    </div>
    @using (Html.BeginForm()) {
        @Html.ValidationSummary(true)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Desc)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Desc)
            @Html.ValidationMessageFor(model => model.Desc)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Desc_html)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Desc_html)
            @Html.ValidationMessageFor(model => model.Desc_html)
        </div>

        <div class="editor-label">
                @Html.LabelFor(m => m.Trade_type)
            </div>
            <div class="editor-field">
                <input type="radio" name="Trade_type" value="1" /> Automated
                <input type="radio" name="Trade_type" value="2" /> Semi automated
                <input type="radio" name="Trade_type" value="4" checked="checked" /> Manual
            </div>

            <div class="editor-label">
                @Html.LabelFor(m => m.Trade_style)
            </div>
            <div class="editor-field">
                <input type="checkbox" name="Trade_style" value="1"/> Scalping
                <input type="checkbox" name="Trade_style" value="2"/> Swing
                <input type="checkbox" name="Trade_style" value="4"/> News trading
            </div>

            <div class="editor-label">
                @Html.LabelFor(m => m.Trade_markets)
            </div>
            <div class="editor-field">
                <input type="checkbox" name="Trade_markets" value="1"/> Forex
                <input type="checkbox" name="Trade_markets" value="2"/> Futures
                <input type="checkbox" name="Trade_markets" value="4"/> CFDs
                <input type="checkbox" name="Trade_markets" value="8"/> Metal
                <input type="checkbox" name="Trade_markets" value="16"/> Stocks
            </div>

            <div class="editor-label">
                @Html.LabelFor(m => m.Trade_sessions)
            </div>
            <div class="editor-field">
                <input type="checkbox" name="Trade_sessions" value="1"/> Asian
                <input type="checkbox" name="Trade_sessions" value="2"/> US
                <input type="checkbox" name="Trade_sessions" value="4"/> Europen
                <input type="checkbox" name="Trade_sessions" value="8"/> UK
            </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

Pipular/Views/Private/Balance.cshtml
@using Pipular.Models;
@using System.Globalization;
@model List<balance>

@{
    ViewBag.Title = "Balance";
}

<h2>Your balance</h2>

<p>
<b>Total: @Model.Sum(m => m.summa).ToString("C2", new CultureInfo("en-US"))</b>
&nbsp;&nbsp;&nbsp;&nbsp;
@Html.ActionLink("Fill up", "FillUpBalance", "Private")&nbsp;|&nbsp;
@Html.ActionLink("Withdraw", "Withdraw", "Private")
</p>

<table>
    <thead>
        <tr>
            <th>
                Type
            </th>
            <th>
                Sum
            </th>
            <th>
                Comment
            </th>
            <th>
                Date
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (balance b in Model)
        {
            <tr>
                <td>
                    @if (b.type == 0)
                    { <text> Fill up </text> }
                    @if (b.type == 1)
                    { <text> Draw </text> }
                    @if (b.type == 2)
                    { <text> For system </text> @b.system }
                </td>
                <td>
                    @b.summa.ToString("C2", new CultureInfo("en-US"))
                </td>
                <td>
                    @b.comment
                </td>
                <td>
                    @b.dt_create
                </td>
            </tr>
}
    </tbody>
</table>

Pipular/Views/Private/ConnectConfiguration.cshtml
@using Pipular.Models;
@model connect

@{
    Layout = "~/Views/Shared/_AdditLayout.cshtml";
}

@section AdditHeader {
    <span><b>Connect configuration</b></span>
    (<a onclick="closeAddit()">cancel</a>)
}

<div id="connect_configuration">
    @using (Ajax.BeginForm("SaveConfiguration", "Private", new { id = Model.nmbr }, new AjaxOptions()
    {
        HttpMethod = "POST",
        OnSuccess = "closeAddit()"
    }))
    {
        @Html.ValidationSummary(true)

        <table>
            <tr>
                <td class="editor-label">
                    @Html.LabelFor(model => model.cfg_morders)  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a id="make_unlim_cfg_morders">unlimited</a><br />
                    @Html.ValidationMessageFor(model => model.cfg_morders)
                </td>
                <td class="editor-field numeric">
                    @Html.TextBoxFor(model => model.cfg_morders)
                </td>
            </tr>
            <tr>
                <td class="editor-label">
                    @Html.LabelFor(model => model.cfg_mvolume) &nbsp;&nbsp;
                    <a id="make_unlim_cfg_mvolume">unlimited</a><br />
                    @Html.ValidationMessageFor(model => model.cfg_mvolume)
                </td>
                <td class="editor-field numeric">
                    @Html.TextBoxFor(model => model.cfg_mvolume)
                </td>
            </tr>
            <tr>
                <td class="editor-field">
                    <input type="radio" name="cfg_uvfs" id="cfg_uvfs1" value="1" @if(Model.cfg_uvfs == 1) {<text>checked="checked"</text>} />
                    <label for="cfg_uvfs1">Use volume from signal</label>
                </td>
                <td class="editor-field"></td>
            </tr>
            <tr>
                <td class="editor-field">
                    <input type="radio" name="cfg_uvfs" id="cfg_uvfs2" value="2" data-activefor="cfg_koeff" @if(Model.cfg_uvfs == 2) {<text>checked="checked"</text>} />
                    <label for="cfg_uvfs2">Koefficient to change volume</label><br />
                    @Html.ValidationMessageFor(model => model.cfg_koeff)
                </td>
                <td class="editor-field numeric">@Html.TextBoxFor(model => model.cfg_koeff)</td>
            </tr>
            <tr>
                <td class="editor-field">
                    <input type="radio" name="cfg_uvfs" id="cfg_uvfs3" value="3" data-activefor="cfg_fixed" @if(Model.cfg_uvfs == 3) {<text>checked="checked"</text>} />
                    <label for="cfg_uvfs3">Fixed volume</label><br />
                    @Html.ValidationMessageFor(model => model.cfg_fixed)
                </td>
                <td class="editor-field numeric">@Html.TextBoxFor(model => model.cfg_fixed)</td>
            </tr>
            <tr>
                <td class="editor-field">
                    <input type="radio" name="cfg_uvfs" id="cfg_uvfs4" value="4" data-activefor="cfg_percent" @if(Model.cfg_uvfs == 4) {<text>checked="checked"</text>} />
                    <label for="cfg_uvfs4">Volume by percent from free margin</label><br />
                    @Html.ValidationMessageFor(model => model.cfg_percent)
                </td>
                <td class="editor-field numeric">
                    @Html.TextBoxFor(model => model.cfg_percent)                  
                </td>
            </tr>
            <tr>
                <td class="editor-label">
                    <input type="submit" value="Save" />
                </td>
                <td></td>
            </tr>
        </table>
    }
</div>

<script type="text/javascript">
    $(document).ready(function () {
        /*
        $('#koeff').spinner({ min: 0.01, max: 100, step: 0.01, width: 20 });
        $('#lot').spinner({ min: 0.01, max: 100, step: 0.01, width: 20 });
        $('#percent').spinner({ min: 1, max: 100, step: 1, width: 20 });
        $('#max_orders').spinner({ min: 1, max: 100, step: 1, width: 20 });
        $('#sum_volume').spinner({ min: 0.01, max: 100, step: 0.01, width: 20 });

        */

        $('#cfg_fixed').val($('#cfg_fixed').val() / 100);
        $('#cfg_mvolume').val($('#cfg_mvolume').val() / 100);

        (function () {
            $.fn.zeroIsUnlimited = function (method) {
                return this.each(function () {
                    var textBox = $(this);

                    var label = $("<div class=\"unlimited\">unlimited</div>").hide().appendTo(textBox.parent());

                    var unlimitedLabel = function () {
                        textBox.hide();
                        label.show();
                    }

                    if (textBox.val() == "0") unlimitedLabel();

                    textBox.mouseleave(function () {
                        if (textBox.val() == "0" || textBox.val() == "") {
                            unlimitedLabel();
                            textBox.val("0");
                        }
                    });

                    label.hover(function () { label.hide(); textBox.show() });

                    var makeUnlimited = function () {
                        textBox.val("0");
                        unlimitedLabel();
                    }

                    $("#make_unlim_" + textBox.attr('id')).click(makeUnlimited)
                });
            }
        })(jQuery);

        $("#connect_configuration").find("#cfg_morders, #cfg_mvolume").zeroIsUnlimited();
        $("#connect_configuration input[type=radio]").linkedRadio();
    });
</script>

Pipular/Views/Private/ConnectDetails.cshtml
@using Pipular;
@using Pipular.Models;
@model Dictionary<string, string>

@{
    ViewBag.Title = "Connect details";
    Layout = "~/Views/Shared/_AdditLayout.cshtml";
}

@section AdditHeader {
    <div class="left">
        <span class="system_name"><b>@Model["system_name"] connect details</b></span>
        (<a onclick="closeAddit()">cancel</a>)
    </div>
    <div class="clear"></div>
}

<div id="SystemDetails">
    @if (ViewData["start"] != null && ViewData["stop"] != null)
    {
        <b>Period from <span class="underline red_text">@ViewData["start"]</span> to <span class="underline red_text">@ViewData["stop"]</span></b>
    }
    <div class="graph_buttons">
        <span id="profit_chart_button">Switch to Profit</span>
        <span id="pips_chart_button">Switch to Pips</span>
    </div>

    <canvas id="canvasGraph" width="980" height="400"></canvas>

    <div id="statistic" class="block">
        <div class="header">
            <div class="caption left">Statistics</div>
            @using(Html.ExpanderIcon("system_statistics"))
            {
                <div class="header_button right">
                    <div class="icon"><i class="icon-arrow-up"></i></div>
                </div>
            }
        </div>
        <div class="content" id="system_statistics">
            @Html.Partial("../Home/SystemStatistic", ViewData["statistic"])
        </div>
    </div>

    <div id="trade_info" class="notebook_wrapper">
        <div class="notebook">
            <div class="tab selected" data-id="#history">
                <div class="caption">History</div>
                <div class="cover"></div>
            </div>
            <div class="tab" data-id="#trades">
                <div class="caption">Open trades</div>
                <div class="cover"></div>
            </div>
            <div class="message right">
                
            </div>
        </div>
        <div class="content">
            <div class="tab_panel current" id="history">@Html.Partial("HistoryTable", (IQueryable<history>)ViewData["history_connect"])</div>
            <div class="tab_panel" id="trades">@Html.Partial("TradesTable", (IQueryable<trade>)ViewData["trade_connect"])</div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('#trade_info').notebook();
        // get chart data
        $.ajax({
            type: 'GET',
            cache: false,
            url: '@Html.Raw(Url.Action("ConnectHistory", "Chart", new { system = (int)ViewBag.System, connect = (int)ViewBag.Connect, start = ViewData["start"], stop = ViewData["stop"] }))',
            success: function (result) { drawSystemChart(result, "canvasGraph", "profit_chart_button", "pips_chart_button"); }
        });

        readCookieElements();
        $("#statistic .expanderIcon").expanderIcon();
    });
</script>

Pipular/Views/Private/GoCopyError.cshtml
<div id="load_error">@ViewBag.Error</div>

Pipular/Views/Private/LeadPanel.cshtml
@using Pipular;
@using Pipular.Models;
@model List<SystemModel>

<div class="simple_block" id="my_systems">
    <div class="label">Your systems (
        @using(Ajax.BeginActionLink("NewSystem", "Private", null, Constants.additAjaxOptions, null))
        {
            <span>Create New System</span>
        })
    </div>
    @foreach (SystemModel sys in Model)
    {
        @Html.Partial("SystemBlock", sys)
    }
    <div class="clear"></div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        
    });
</script>

Pipular/Views/Private/MyConnects.cshtml
@{
    ViewBag.Title = "My connects";
}

<h2>My connects</h2>
<p>
@Html.ActionLink("New connect", "Systems", "Home")
</p>

@Html.Action("MyConnectsTable", "Private")

Pipular/Views/Private/SelectPortfolio.cshtml
@using Pipular;
@using Pipular.Models;
@model List<Portfolio>

<script type="text/javascript">
    $(document).ready(function () {
        $('#submit_portfolio').click(function () {
            $('#submit_portfolio').button('disable');
            $('#min_wait').show();
            var portfolio = $('#portfolio_id').val();

            $.ajax({
                url: '@Url.Action("AddConnectToPortfolio", "Private")' + '?connect_id=@ViewBag.ConnectId' + '&portfolio_id=' + portfolio,
                cache: false,
                success: function () { $('#popup_content').html('@Html.ActionLink("Go to dashboard portfolios", "Dashboard", "Private", null, null, "follow_panel", null, null)'); }
            }).done(function (result) {
                if ($('#noportfolios').length > 0) {
                    $('#noportfolios').find('.connect_block#' + '@ViewBag.ConnectId').appendTo('.portfolio_block#' + portfolio + ' .connects .expandable');
                }
            });
        });
    });
</script>

<div id="SelectPortfolio">
    @using (Ajax.BeginForm("AddConnectToPortfolio", "Private", new AjaxOptions()
        {
            UpdateTargetId = "popup_content",
            HttpMethod = "POST",
            OnSuccess = "closeAddit(); replaceTo('#freeConnects')"
        }))
    {
        <table class="portfolioTable">
        @foreach (Portfolio p in Model)
        {
            <tr>
                <td></td>
                <td>
                    @Html.RadioButtonLabel(
                        "portfolio_id",
                        p.number + " " + p.company,
                        p.nmbr,
                        new { id = "account" + p.nmbr },
                        false,
                        p.connects.Any(c => c.system_nmbr == ViewBag.SystemId))
                </td>
            </tr>
        }
        </table>
        <input type="hidden" name="connect_id" value="@ViewBag.ConnectId" />
        <input type="submit" value="Select" />
    }
    <p>
        @Html.ActionLink("Go to dashboard portfolios", "Dashboard", "Private", null, null, "follow_panel", null, null)
    </p> 
</div>